"""
Cognitive SOC Phase 2 — Behavioral Alert Lambda
Formats and sends behavioral anomaly alerts.
Integrates with Phase 1 notifier for consistent alerting.
"""

import json
import logging
import os
import boto3
import urllib.request
from datetime import datetime

logger = logging.getLogger()
logger.setLevel(os.environ.get("LOG_LEVEL", "INFO"))

sns_client     = boto3.client("sns")
lambda_client  = boto3.client("lambda")
secretsmanager = boto3.client("secretsmanager")
SNS_TOPIC_ARN  = os.environ.get("SNS_ALERT_TOPIC_ARN", "")
ENVIRONMENT    = os.environ.get("ENVIRONMENT", "dev")

SEVERITY_EMOJI = {"CRITICAL": "🚨🧬", "HIGH": "🔴🧬", "MEDIUM": "🟠🧬"}


def lambda_handler(event, context):
    finding       = event.get("finding", {})
    anomaly       = event.get("anomaly_result", {})
    escalate      = event.get("escalate", False)

    severity      = anomaly.get("severity", "MEDIUM")
    emoji         = SEVERITY_EMOJI.get(severity, "⚠️🧬")
    entity_id     = anomaly.get("entity_id", "unknown")
    score         = anomaly.get("composite_score", 0)
    dim_scores    = anomaly.get("dimension_scores", {})
    signal        = anomaly.get("signal", {})

    # Send SNS alert
    if SNS_TOPIC_ARN:
        send_sns(entity_id, severity, score, dim_scores, signal, emoji)

    # Send Slack alert
    webhook = get_secret("cognitive-soc/slack-webhook")
    if webhook:
        send_slack(entity_id, severity, score, dim_scores, signal, emoji, webhook, anomaly)

    return {"alerted": True, "entity_id": entity_id, "severity": severity}


def send_sns(entity_id, severity, score, dim_scores, signal, emoji):
    subject = f"{emoji} [{severity}] Behavioral DNA Anomaly: {entity_id}"[:100]
    message = f"""
COGNITIVE SOC — BEHAVIORAL DNA ALERT
======================================
Entity:        {entity_id}
Severity:      {severity}
Anomaly Score: {score:.1f} / 100
Detected At:   {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}

ANOMALY BREAKDOWN
-----------------
Temporal Score:  {dim_scores.get('temporal_score', 0):.1f}  (unusual time of activity)
Geographic Score:{dim_scores.get('geo_score', 0):.1f}  (unusual region/location)
Service Score:   {dim_scores.get('service_score', 0):.1f}  (unusual AWS service accessed)
Action Score:    {dim_scores.get('action_score', 0):.1f}  (unusual API action)
Sequence Score:  {dim_scores.get('sequence_score', 0):.1f}  (unusual action sequence)

TRIGGERING EVENT
----------------
Time:    {signal.get('timestamp', 'unknown')}
Service: {signal.get('service', 'unknown')}
Action:  {signal.get('action', 'unknown')}
Region:  {signal.get('aws_region', 'unknown')}
Source IP:{signal.get('source_ip', 'unknown')}

This alert was generated by Cognitive SOC Behavioral DNA Engine.
Even if GuardDuty shows no findings, this entity's behavior has
deviated significantly from their established baseline.
"""
    sns_client.publish(TopicArn=SNS_TOPIC_ARN, Subject=subject, Message=message)


def send_slack(entity_id, severity, score, dim_scores, signal, emoji, webhook, anomaly):
    """Send rich Slack alert with behavioral breakdown."""

    # Build dimension score bar chart (text-based)
    def score_bar(s):
        filled = int(s / 10)
        return "█" * filled + "░" * (10 - filled) + f" {s:.0f}"

    blocks = [
        {"type": "header",
         "text": {"type": "plain_text", "text": f"{emoji} Behavioral DNA Anomaly — {severity}"}},
        {"type": "section", "fields": [
            {"type": "mrkdwn", "text": f"*Entity*\n`{entity_id}`"},
            {"type": "mrkdwn", "text": f"*Anomaly Score*\n*{score:.1f}* / 100"},
            {"type": "mrkdwn", "text": f"*Service*\n{signal.get('service','unknown')}"},
            {"type": "mrkdwn", "text": f"*Action*\n`{signal.get('action','unknown')}`"},
            {"type": "mrkdwn", "text": f"*Region*\n{signal.get('aws_region','unknown')}"},
            {"type": "mrkdwn", "text": f"*Source IP*\n{signal.get('source_ip','unknown')}"},
        ]},
        {"type": "section", "text": {"type": "mrkdwn", "text": (
            "*🧬 Behavioral DNA Breakdown*\n"
            f"```\n"
            f"Temporal  {score_bar(dim_scores.get('temporal_score',0))}\n"
            f"Geographic{score_bar(dim_scores.get('geo_score',0))}\n"
            f"Service   {score_bar(dim_scores.get('service_score',0))}\n"
            f"Action    {score_bar(dim_scores.get('action_score',0))}\n"
            f"Sequence  {score_bar(dim_scores.get('sequence_score',0))}\n"
            f"```"
        )}},
        {"type": "section", "text": {"type": "mrkdwn",
         "text": f"⚠️ *This alert fired from Behavioral DNA — GuardDuty may show no findings.*\nThe entity's behavior has deviated from their established baseline of *{anomaly.get('observations',0):,}* historical API calls."}},
        {"type": "context", "elements": [{"type": "mrkdwn",
         "text": f"Cognitive SOC Behavioral DNA | {ENVIRONMENT.upper()} | {datetime.utcnow().strftime('%H:%M:%S UTC')}"}]},
    ]

    try:
        req = urllib.request.Request(webhook,
            data=json.dumps({"blocks": blocks}).encode(),
            headers={"Content-Type": "application/json"})
        urllib.request.urlopen(req, timeout=5)
    except Exception as e:
        logger.warning(f"Slack alert failed (non-fatal): {e}")


def get_secret(name):
    try:
        return secretsmanager.get_secret_value(SecretId=name).get("SecretString", "")
    except Exception:
        return None
